version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - composer install --no-progress --no-suggest
      # Start Mysql if you need it
      - sudo yum-config-manager --disable mysql80-community
      - sudo yum-config-manager --enable mysql57-community
      - yum update -y
      - yum install -y mysql-community-server
      - /usr/bin/mysql -s /bin/bash -c "/usr/sbin/mysqld" &
      - /usr/bin/mysql  -u root -e "GRANT ALL ON *.* TO 'test'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
      - mysqladmin -u test create test
  pre_build:
    commands:
      - ./vendor/bin/phpunit
  build:
    commands:
      - composer install --no-dev --no-progress --no-suggest
  post_build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template-export.yml
    - template-configuration.json
